name: MyPet-NPC
main: de.keyle.mypet.npc.MyPetNpcPlugin
version: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}
author: Keyle
website: ${project.url}
depend: [Citizens]
softdepend: [MyPet]